### ISSUE TITLE
Uruchamiania strony na localhost:8080

### ISSUE THREAD

**Issue by MacEncrypted** [cole1911/uam-email-client#8]
W katalogu głównym aplikacji:

> grunt includeSourced

Oraz uruchomienie w katalogu /server:

> server.js

**Comment by MacEncrypted** [comment]
Poprawka:

> grunt includeSource

Poprawka:

> node server.js

**Comment by gregory16mix** [comment]
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Grzes\Desktop\uam-email-client-develop\uam-e
mail-client\server\server.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

Jakieś pomysły co mam źle?

**Comment by cole1911** [comment]
npm install w katalogu server

2015-02-18 23:14 GMT+01:00 Gregory notifications@github.com:
